import type { SurveyTemplate } from "@/shared/types/domain";

export const SURVEY_TEMPLATES: SurveyTemplate[] = [
  {
    id: "template-1",
    title: "취미와 관심사 설문",
    description: "당신의 취미와 관심사를 알아보는 설문입니다.",
    aiGenerated: false,
    createdAt: new Date(),
    questions: [
      {
        id: "q1-1",
        surveyTemplateId: "template-1",
        text: "주말에 가장 즐겨하는 활동은?",
        weight: 2,
        orderIndex: 1,
        createdAt: new Date(),
        options: [
          {
            id: "o1-1-1",
            text: "영화/드라마 보기",
            value: "MOVIE",
            icon: "🎬",
          },
          { id: "o1-1-2", text: "운동/스포츠", value: "SPORTS", icon: "⚽" },
          { id: "o1-1-3", text: "독서", value: "READING", icon: "📚" },
          { id: "o1-1-4", text: "게임", value: "GAMING", icon: "🎮" },
          { id: "o1-1-5", text: "음악 감상", value: "MUSIC", icon: "🎵" },
        ],
      },
      {
        id: "q1-2",
        surveyTemplateId: "template-1",
        text: "좋아하는 음악 장르는?",
        weight: 2,
        orderIndex: 2,
        createdAt: new Date(),
        options: [
          { id: "o1-2-1", text: "K-POP", value: "KPOP", icon: "��" },
          { id: "o1-2-2", text: "클래식", value: "CLASSICAL", icon: "🎻" },
          { id: "o1-2-3", text: "락/메탈", value: "ROCK", icon: "��" },
          { id: "o1-2-4", text: "재즈", value: "JAZZ", icon: "🎷" },
          { id: "o1-2-5", text: "힙합", value: "HIPHOP", icon: "🎧" },
        ],
      },
      {
        id: "q1-3",
        surveyTemplateId: "template-1",
        text: "여행을 갈 때 선호하는 장소는?",
        weight: 2,
        orderIndex: 3,
        createdAt: new Date(),
        options: [
          { id: "o1-3-1", text: "해변", value: "BEACH", icon: "🏖️" },
          { id: "o1-3-2", text: "산/자연", value: "MOUNTAIN", icon: "⛰️" },
          { id: "o1-3-3", text: "도시", value: "CITY", icon: "🌆" },
          {
            id: "o1-3-4",
            text: "역사 유적지",
            value: "HISTORICAL",
            icon: "🏛️",
          },
          { id: "o1-3-5", text: "테마파크", value: "THEMEPARK", icon: "🎡" },
        ],
      },
    ],
  },
  {
    id: "template-2",
    title: "성격과 가치관 설문",
    description: "당신의 성격과 가치관을 알아보는 설문입니다.",
    aiGenerated: false,
    createdAt: new Date(),
    questions: [
      {
        id: "q2-1",
        surveyTemplateId: "template-2",
        text: "스트레스 해소 방법은?",
        weight: 2,
        orderIndex: 1,
        createdAt: new Date(),
        options: [
          { id: "o2-1-1", text: "운동", value: "EXERCISE", icon: "��" },
          { id: "o2-1-2", text: "음악 감상", value: "MUSIC", icon: "🎵" },
          { id: "o2-1-3", text: "영화/드라마", value: "MOVIE", icon: "🎬" },
          { id: "o2-1-4", text: "독서", value: "READING", icon: "📚" },
          { id: "o2-1-5", text: "게임", value: "GAMING", icon: "🎮" },
        ],
      },
      {
        id: "q2-2",
        surveyTemplateId: "template-2",
        text: "인생에서 가장 중요하게 생각하는 것은?",
        weight: 3,
        orderIndex: 2,
        createdAt: new Date(),
        options: [
          { id: "o2-2-1", text: "가족", value: "FAMILY", icon: "👨‍👩‍👧‍👦" },
          { id: "o2-2-2", text: "건강", value: "HEALTH", icon: "💪" },
          { id: "o2-2-3", text: "경력", value: "CAREER", icon: "💼" },
          { id: "o2-2-4", text: "재정", value: "FINANCE", icon: "��" },
          { id: "o2-2-5", text: "취미", value: "HOBBY", icon: "🎯" },
        ],
      },
      {
        id: "q2-3",
        surveyTemplateId: "template-2",
        text: "친구를 사귈 때 중요하게 생각하는 것은?",
        weight: 2,
        orderIndex: 3,
        createdAt: new Date(),
        options: [
          { id: "o2-3-1", text: "성격", value: "PERSONALITY", icon: "��" },
          { id: "o2-3-2", text: "관심사", value: "INTERESTS", icon: "🎯" },
          { id: "o2-3-3", text: "가치관", value: "VALUES", icon: "💭" },
          {
            id: "o2-3-4",
            text: "소통 방식",
            value: "COMMUNICATION",
            icon: "��",
          },
          { id: "o2-3-5", text: "생활 패턴", value: "LIFESTYLE", icon: "⏰" },
        ],
      },
    ],
  },
  {
    id: "template-3",
    title: "라이프스타일 설문",
    description: "당신의 일상생활과 라이프스타일을 알아보는 설문입니다.",
    aiGenerated: false,
    createdAt: new Date(),
    questions: [
      {
        id: "q3-1",
        surveyTemplateId: "template-3",
        text: "일상생활에서 가장 중요하게 생각하는 것은?",
        weight: 2,
        orderIndex: 1,
        createdAt: new Date(),
        options: [
          { id: "o3-1-1", text: "수면", value: "SLEEP", icon: "😴" },
          { id: "o3-1-2", text: "운동", value: "EXERCISE", icon: "💪" },
          { id: "o3-1-3", text: "식사", value: "MEAL", icon: "🍽️" },
          { id: "o3-1-4", text: "취미", value: "HOBBY", icon: "🎯" },
          { id: "o3-1-5", text: "일", value: "WORK", icon: "💼" },
        ],
      },
      {
        id: "q3-2",
        surveyTemplateId: "template-3",
        text: "건강관리를 위해 하는 활동은?",
        weight: 2,
        orderIndex: 2,
        createdAt: new Date(),
        options: [
          {
            id: "o3-2-1",
            text: "규칙적인 운동",
            value: "REGULAR_EXERCISE",
            icon: "💪",
          },
          {
            id: "o3-2-2",
            text: "건강한 식단",
            value: "HEALTHY_DIET",
            icon: "��",
          },
          {
            id: "o3-2-3",
            text: "충분한 수면",
            value: "ENOUGH_SLEEP",
            icon: "😴",
          },
          {
            id: "o3-2-4",
            text: "스트레스 관리",
            value: "STRESS_MANAGEMENT",
            icon: "🧘",
          },
          {
            id: "o3-2-5",
            text: "정기 검진",
            value: "REGULAR_CHECKUP",
            icon: "��‍⚕️",
          },
        ],
      },
      {
        id: "q3-3",
        surveyTemplateId: "template-3",
        text: "취미 활동에 투자하는 시간은?",
        weight: 2,
        orderIndex: 3,
        createdAt: new Date(),
        options: [
          {
            id: "o3-3-1",
            text: "1시간 미만",
            value: "LESS_THAN_1H",
            icon: "⏰",
          },
          { id: "o3-3-2", text: "1-3시간", value: "1_3H", icon: "⏰" },
          { id: "o3-3-3", text: "3-5시간", value: "3_5H", icon: "⏰" },
          { id: "o3-3-4", text: "5-7시간", value: "5_7H", icon: "⏰" },
          {
            id: "o3-3-5",
            text: "7시간 이상",
            value: "MORE_THAN_7H",
            icon: "⏰",
          },
        ],
      },
    ],
  },
];
